function estimator = doaEst(doa, ula, scan_axis, num, fc)
switch doa
    case 'MVDR'
        estimator = phased.MVDREstimator('SensorArray',ula,...
            'OperatingFrequency',fc,'ScanAngles',scan_axis,...
            'DOAOutputPort',true,'NumSignals', num);
    case 'MUSIC'
        estimator = phased.MUSICEstimator('SensorArray',ula,...
            'OperatingFrequency',fc,'ScanAngles',scan_axis,...
            'DOAOutputPort',true);
    case 'MUSICR'
        estimator = phased.RootMUSICEstimator('SensorArray',ula,...
            'OperatingFrequency',fc);
    case 'Beamscan'
        estimator = phased.BeamscanEstimator('SensorArray',ula,...
            'OperatingFrequency',fc,'ScanAngles',scan_axis,...
            'DOAOutputPort',true,'NumSignals', num);
    case 'ESPRITE'
        estimator = phased.ESPRITEstimator('SensorArray',ula,...
            'OperatingFrequency',fc);
    case 'ESPRITEBS'
        estimator = phased.BeamspaceESPRITEstimator('SensorArray',ula,...
            'OperatingFrequency',fc);
%     case 'WSFR'
%         estimator = phased.RootWSFEstimator('SensorArray',ula,...
%             'OperatingFrequency',fc);
        %     case 'Monopulse'
        %         estimator = phased.SumDifferenceMonopulseTracker('SensorArray',ula,...
        %             'OperatingFrequency',fc);
    otherwise
        estimator = phased.MVDREstimator('SensorArray',ula,...
    'OperatingFrequency',fc,'ScanAngles',scan_axis,...
    'DOAOutputPort',true,'NumSignals', num);
end