function [rawDataAdj, weights] = mvdrBf(rawData, estimated_angle, magic, ula, fc, c)

    beamformer = phased.MVDRBeamformer('SensorArray',ula,...
'PropagationSpeed',c,'OperatingFrequency',fc,...
'Direction',[estimated_angle;0],'WeightsOutputPort',true, ...
'TrainingInputPort',false, 'DiagonalLoadingFactor', magic);

    [rawDataAdj,weights] = beamformer(rawData); 
    weights = weights.';
