% Examples showing how to use the process file and new functions
% Pulse format is:
% startTime;basePower;transitionType;basePhase;PRI;PW;riseTime;fallTime;pulseShape;span;offset;amplitude;fmFormula;pmFormula;modulationType;delay;phase;continuousPhase

fileProcess = 'PDWCombineProcessFileExample'

%% Example showing debug and saving
multi_pdw(...  
    'function', 'save', ...
    'debugmode', 1, ...
    'processFile', fileProcess)

%% Example showing saving and previewing in VSA
multi_pdw(...  
    'function', 'save,vsa,download', ...
    'debugmode', 0, ...
    'processFile', fileProcess)

%% Examples showing clipping
[~,...
MultiPulseAmplitudeShiftInDB1,...
~, iqData1, ~] = ...
multi_pdw(...  
    'function', 'save', ...
    'debugmode', 0, ...
    'maxamplitude', 10, ...
    'cliptomaxamplitude', true, ...
    'processFile', fileProcess, 'starttime', 10E-6,'offsettime', 0);

[~,...
MultiPulseAmplitudeShiftInDB2,...
~, iqData2, ~] = ...
multi_pdw(...  
    'function', 'save', ...
    'debugmode', 0, ...
    'maxamplitude', 2, ...
    'cliptomaxamplitude', true, ...
    'processFile', fileProcess, 'starttime', 10E-6,'offsettime', 0);

iq2 = MultiPulseAmplitudeShiftInDB2 + 20*log10(abs(iqData2)+ 0.001 * rand(length(iqData2), 1));
iq1 = MultiPulseAmplitudeShiftInDB1 + 20*log10(abs(iqData1)+ 0.001 * rand(length(iqData1), 1));
     
figure('NumberTitle', 'off', 'Name', 'Clipping Example'); plot(iq1); hold on; plot(iq2)
grid on   
legend('Clipped to 10 dBm', 'Clipped to 2 dBm')

%% Examples showing time offset
[~,...
MultiPulseAmplitudeShiftInDB1,...
OffsetTime1, iqData1, ~] = ...
multi_pdw(...  
    'function', 'save', ...
    'debugmode', 0, ...
    'processFile', fileProcess, 'starttime', 10E-6,'offsettime', 0);

[~,...
MultiPulseAmplitudeShiftInDB2,...
OffsetTime2, iqData2, ~] = ...
multi_pdw(...  
    'function', 'save', ...
    'debugmode', 0, ...
    'processFile', fileProcess, 'starttime', 10E-6,'offsettime', 1);

iq2 = MultiPulseAmplitudeShiftInDB2 + 20*log10(abs(iqData2)+ 0.001 * rand(length(iqData2), 1));
iq1 = MultiPulseAmplitudeShiftInDB1 + 20*log10(abs(iqData1)+ 0.001 * rand(length(iqData1), 1));
     
figure('NumberTitle', 'off', 'Name', 'Time Offset Example'); plot(iq1); hold on; plot(iq2)
grid on   
legend('No time offset', 'Time offset')
